# Goated theme:  https://github.com/sirius93/cayman-theme-custom

remote_theme: sirius93/cayman-theme-custom
plugins:
- jekyll-remote-theme
title: Discorsa
description: Assetto Corsa plugin for Discord
darkmode: false
hide_first_title: false # Useful if README.md is used on both github and pages
syntax_theme: # Leave empty for default, otherwise link to a pygments stylesheet
color:
    gradient_left: "#a88ee3"
    gradient_right: "#5f2ba5"
    header: "#ead3f1"
    section_title: "#155799" # this default to gradient_color
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
buttons:
    zip_url: https://discord.gg/DPTCrxawBx
    zip_title: Join Support Server
    zip_hide: false
    tar_url: https://discord.com/api/oauth2/authorize?client_id=1111709452526161920&redirect_uri=https%3A%2F%2Fdiscorsa-webserver-endpoint.up.railway.app%2Fo2auth&response_type=code&scope=identify%20connections
    tar_title: Register on Discorsa
    tar_hide: false
    github_hide: true
show_downloads: true
favicon: none
logo_url: ./logo.png # Either absolute or relative url
