remote_theme: sirius93/cayman-theme-custom
plugins:
- jekyll-remote-theme
title: Discorsa
description: Why are you here...
darkmode: false
hide_first_title: false # Useful if README.md is used on both github and pages
syntax_theme: ./syntax.css # Leave empty for default, otherwise link to a pygments stylesheet
color:
    gradient_left: "#7b58dc"
    gradient_right: "#5f2ba5"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
buttons:
    zip_url: http://example.com/
    zip_title: Title
    zip_hide: true
    tar_url: http://example.com/
    tar_title: Title
    tar_hide: true
    github_hide: true # hides "View on Github"
favicon: none
logo_url: ./logo.png # Either absolute or relative url
