remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Discorsa Homepage
description: Under construction?
show_downloads: False

github:
  repository_url: https://discord.gg/DPTCrxawBx
# Jekyll is weird and wont add a third button so we need to do whatever this is
